version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myproduct
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306" 
    networks:
      - springboot-mysql-net

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    depends_on:
      - mysqldb
      
    networks:
      springboot-mysql-net:
    restart: on-failure
      
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/myproduct?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

networks:
  springboot-mysql-net:
    driver: bridge
