version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myproduct
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8091:8080"
